// src/services/invoicePdf.service.js
import PDFDocument from "pdfkit";
import { InvoiceModel } from "../models/Invoice.model.js";

/**
 * generatePdfStream(invoice) -> returns function that pipes PDF to response
 *
 * We create PDF programmatically using PDFKit and stream it to Express res.
 * Keeps memory low and no external dependencies.
 */

function formatCurrency(n) {
  return "৳" + Number(n || 0).toFixed(2);
}

export async function streamInvoicePdfById(invoiceId, res) {
  const inv = await InvoiceModel.findById(invoiceId).lean();
  if (!inv) {
    res.status(404).json({ ok: false, error: "Invoice not found" });
    return;
  }
  return streamInvoicePdf(inv, res);
}

export function streamInvoicePdf(invoice, res) {
  // response headers for inline display (browser) and fallback download
  const filename = `invoice-${invoice.invoiceNumber ?? invoice._id}.pdf`;
  res.setHeader("Content-Type", "application/pdf");
  // inline (open in new tab) — change to attachment to force download
  res.setHeader("Content-Disposition", `inline; filename="${filename}"`);

  const doc = new PDFDocument({ size: "A4", margin: 40 });

  doc.pipe(res);

  // --- Header ---
  doc
    .fontSize(18)
    .fillColor("#0f766e")
    .text(invoice.companyName || "Your Company", { continued: true });
  doc
    .fontSize(10)
    .fillColor("#444")
    .text(`     Invoice: ${invoice.invoiceNumber || ""}`, { align: "right" });
  doc.moveDown(0.2);
  doc
    .fontSize(10)
    .fillColor("#666")
    .text(
      `Date: ${
        invoice.createdAt ? new Date(invoice.createdAt).toLocaleString() : ""
      }`,
      { align: "right" }
    );
  doc.moveDown(1);

  // Billing
  doc.fontSize(12).fillColor("#333").text("Billed To:", { underline: false });
  const name =
    (invoice.customerContact && invoice.customerContact.name) ||
    invoice.customerName ||
    "";
  if (name) doc.fontSize(11).text(name);
  if (invoice.customerContact?.email) doc.text(invoice.customerContact.email);
  if (invoice.billingAddress) doc.text(invoice.billingAddress);
  doc.moveDown(0.8);

  // Table Header
  const startX = doc.x;
  doc
    .fontSize(10)
    .fillColor("#111")
    .text("Description", startX, doc.y, { width: 300 });
  doc.text("Qty", startX + 310, doc.y, { width: 50, align: "right" });
  doc.text("Unit", startX + 370, doc.y, { width: 80, align: "right" });
  doc.text("Line", startX + 460, doc.y, { width: 80, align: "right" });
  doc.moveDown(0.3);
  doc
    .moveTo(startX, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor("#e6e6e6")
    .lineWidth(1)
    .stroke();
  doc.moveDown(0.3);

  // Items
  (invoice.items || []).forEach((it) => {
    const desc = it.description || "";
    const qty = it.quantity ?? 0;
    const unit = Number(it.unitPrice ?? 0).toFixed(2);
    const line = Number(it.lineTotal ?? qty * (it.unitPrice ?? 0)).toFixed(2);

    doc.fontSize(10).fillColor("#111").text(desc, { width: 300 });
    const y = doc.y;
    doc.text(String(qty), startX + 310, y, { width: 50, align: "right" });
    doc.text(unit, startX + 370, y, { width: 80, align: "right" });
    doc.text(line, startX + 460, y, { width: 80, align: "right" });
    doc.moveDown(0.4);
  });

  // Totals
  doc.moveDown(0.6);
  const totalX = startX + 300;
  doc
    .fontSize(10)
    .text("Subtotal:", totalX, doc.y, { width: 200, align: "right" });
  doc.text(formatCurrency(invoice.subtotal), startX + 460, doc.y, {
    width: 80,
    align: "right",
  });
  doc.moveDown(0.2);
  doc.text("Tax:", totalX, doc.y, { width: 200, align: "right" });
  doc.text(formatCurrency(invoice.taxTotal), startX + 460, doc.y, {
    width: 80,
    align: "right",
  });
  doc.moveDown(0.2);
  doc.text("Discount:", totalX, doc.y, { width: 200, align: "right" });
  doc.text(formatCurrency(invoice.discountAmount), startX + 460, doc.y, {
    width: 80,
    align: "right",
  });
  doc.moveDown(0.4);
  doc
    .fontSize(12)
    .font("Helvetica-Bold")
    .text("Total:", totalX, doc.y, { width: 200, align: "right" });
  doc.text(formatCurrency(invoice.total), startX + 460, doc.y, {
    width: 80,
    align: "right",
  });

  doc.moveDown(1);
  if (invoice.notes) {
    doc.fontSize(10).font("Helvetica").text("Notes:", { underline: true });
    doc.moveDown(0.2);
    doc.fontSize(9).text(String(invoice.notes));
  }

  // Footer
  doc.moveDown(2);
  doc
    .fontSize(8)
    .fillColor("#777")
    .text(`Generated by Admin Panel`, { align: "center" });

  doc.end();
}
